Step12/validation
jfchen19/task_web pull request #10
Opened 2021-03-09 11:16 UTC by jfchen19

2021-03-10 03:50 UTC, shes50103 requested changes

2021-03-10 03:50 UTC, shes50103 commented on app/models/task.rb
> +    end
會比較建議要翻譯的話到 view 再翻譯
讓錯誤訊息用英文寫死就好

2021-03-10 03:50 UTC, shes50103 commented on app/models/task.rb
> +    return if end_time.blank? || start_time.blank?
`return if end_time.blank? || start_time.blank?`
不加的話可以嗎？
錯誤會在 

```
validates :title, :subject, :start_time, :end_time, presence: true
```
就先擋下來嗎？

2021-03-10 03:50 UTC, shes50103 commented on spec/factories/task.rb
> +    end_time { Faker::Time.between(from: DateTime.now + 3, to: DateTime.now + 10) }
**nitpick**

比起這樣寫
```
DateTime.now + 3
```
更建議寫具體時間，可能像這樣

```
DateTime.now + 3.days
```

2021-03-10 03:50 UTC, shes50103 commented on spec/support/shoulda_matchers.rb
> +  # byebug
`# byebug` 記得拿掉

2021-03-10 03:50 UTC, shes50103 commented on spec/models/tasks_spec.rb
> +                                )
應該用 factory bot 來產生

2021-03-10 03:50 UTC, shes50103 commented on db/migrate/20210308080810_add_start_time_and_end_time_to_task.rb
> +    add_column :tasks, :end_time, :datetime
會用這兩欄位來排序的話
會需要加 index

2021-03-10 09:07 UTC, jfchen19 commented on app/models/task.rb
> +    return if end_time.blank? || start_time.blank?
目前試出來的結果是如果開始時間晚於結束時間，可以正常顯示錯誤訊息；
但是如果開始時間以及結束時間只要有任何一個或是兩個都沒有填入的話，就會出現錯誤。
錯誤訊息：```if end_time < start_time``` undefined method `<' for nil:NilClass
所以才會把 ```return if end_time.blank? || start_time.blank?``` 加上去

2021-03-10 09:12 UTC, jfchen19 commented on db/migrate/20210308080810_add_start_time_and_end_time_to_task.rb
> +    add_column :tasks, :end_time, :datetime
因為目前用```created_at```在排序，
如果要把```start_time``` ```end_time```加 index 的話，```created_at```也需要加嗎？
還是```created_at```本身就有 index 呢？

2021-03-10 09:15 UTC, jfchen19 commented on app/models/task.rb
> +    end
目前 model 的錯誤訊息在 view 的寫法如下：
```
<% if @task.errors.any? %>
  <ul>
  <% @task.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>
```
可以提示一下在這邊寫錯誤訊息的翻譯要怎麼寫嗎？😅

2021-03-10 09:24 UTC, shes50103 commented on db/migrate/20210308080810_add_start_time_and_end_time_to_task.rb
> +    add_column :tasks, :end_time, :datetime
有沒有 index 可以去檢查 `schema.rb` 預設應該只有 primary key 也就是 id 有 index.

2021-03-10 09:28 UTC, shes50103 commented on app/models/task.rb
> +    end
可能像這樣
```
<% if @task.errors.any? %>
  <ul>
  <% @task.errors.full_messages.each do |message| %>
    <li> <%= t(message)%> </li>
  <% end %>
  </ul>
<% end %>
```

但可能就不是用 full_messages 可能要找找看有沒有能代表特定錯誤狀況的縮寫或編號

2021-03-11 10:22 UTC, shes50103 approved these changes

2021-03-11 10:22 UTC, merged